### ISSUE TITLE
Upscaler not working in v3.17

### ISSUE THREAD

**Issue by robovajda** [artmamedov/artroom-stable-diffusion#12]
As the title says, the upscaler is not working on my PC after 3.17 update.
After opening the artroom as administrator and runing any upscaling algorithm I get the following error:

Running....
If it freezes, please try pressing enter. Doesn't happen often but could happen once in a while

C:\Program Files\Artroom\stable-diffusion\src\gfpgan>conda.bat activate
Processing DALL·E 2022-09-20 08.28.02.png ...
Traceback (most recent call last):
  File "inference_gfpgan.py", line 174, in <module>
    main()
  File "inference_gfpgan.py", line 134, in main
    cropped_faces, restored_faces, restored_img = restorer.enhance(
  File "C:\Users\fenix\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Artroom\stable-diffusion\src\gfpgan\gfpgan\utils.py", line 109, in enhance
    self.face_helper.read_image(img)
  File "C:\Users\fenix\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 114, in read_image
    if np.max(img) > 256:  # 16-bit image
TypeError: '>' not supported between instances of 'NoneType' and 'int'
ERROR conda.cli.main_run:execute(49): `conda run python inference_gfpgan.py -i C:\Users\fenix/artroom/settings/upscale_queue -o C:\Users\fenix\Desktop\tis -v 1.4 -s 2 --bg_upsampler realesrgan --suffix _upscaled -w 0.5` failed. (See above for error)
Finished!

**Comment by artmamedov** [comment]
Hi,
The upscalers are having a permissions issue when installing. Will fix this in 0.3.18

**Comment by PaintOnBrush** [comment]
I had an issue where the .pth file for the upscaler doesn't download on windows during installation.

**Comment by artmamedov** [comment]
Hi! .pth file should be fixed in this new install (RealESRGAN didn't make the cut for this patch, will be integrated during weekend's patch)
