### ISSUE TITLE
Assertion out of bounds? Need some help to fix it, thanks.

### ISSUE THREAD

**Issue by hodeidara** [artmamedov/artroom-stable-diffusion#30]
Successfully set up model
Generating...
Prompt: The fellowship of the ring, but if all members were women
Negative Prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Weighted prompts: ['The fellowship of the ring, but if all members were women']
Sampler ddim
seeds used =  [3605081283]
Running DDIM Sampling with 50 timesteps
Decoding image: 100%|██████████████████████████████████████████████████████████████████| 50/50 [00:08<00:00,  5.86it/s]
New image size (512, 512)
seeds used =  [3605081283]
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:145: block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Exception in thread Thread-10 (run_queue):
Traceback (most recent call last):
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Artroom\queue_manager.py", line 210, in run_queue
    self.generate(queue_item)
  File "C:\Program Files\Artroom\queue_manager.py", line 174, in generate
    self.SD.generate(
  File "C:\Program Files\Artroom\stable_diffusion.py", line 600, in generate
    x0 = self.model.sample(
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Artroom\stable-diffusion/optimizedSD\ddpm.py", line 728, in sample
    self.model1.to(self.cdevice)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\hodis\artroom\miniconda3\envs\artroom-ldm\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Balu027** [comment]
Started getting the same issue. First got it when I tried to generate 16:9 pictures and after getting this error I couldn't generate anything until I reinstalled it. Now not even reinstalling helps, not even for 1:1 pictures.
![artroom bug](https://user-images.githubusercontent.com/26222275/220903755-94f3996f-9ef3-464c-a37a-96c5dbee4d90.JPG)

**Comment by Balu027** [comment]
I tested a bit more. The previous version seems to work fine with smaller picture sizes, while bigger pictures will result an out of memory error. With the newest version, small sizes work (in my case, 1:1 up to about 512x512 and 16:9 up to 640x320 with a 4Gb 1050 Ti) and increasing further will result in this issue.
